[package]
name = "translator"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-tui = "8.0.1"
clap = { version = "4.6.5", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
itertools = "0.14.0"
log = "0.4.29"
rangemap = "1.7.1"
ratatui = { version = "0.30", features = ["unstable-widget-ref"] }
ratatui-explorer = "0.3.0"
ratatui-textarea = "0.9.1"
simple_file_logger = "0.4.2"
